android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
AV_SPORT_WEB_URL=http://13.236.134.23
AV_SPORT_API_BASE_URL=http://13.236.134.23
AV_SPORT_UPDATE_MANIFEST_URL=https://raw.githubusercontent.com/anhviet-key/AV-SPORT/main/app-update.json
AV_SPORT_VERSION_NAME=1.1.9
AV_SPORT_VERSION_CODE=20
